---
title: "IV_GROUP_R"
author: "Xinwei Qian"
date: "2022/10/19"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
hotel <- read.csv(file = 'hotel.csv',header = TRUE)
hotel_clean <- hotel[hotel$HOTEL.CLASS != -1,]
```


```{r}
hotel_clean$HOTEL.CLASS.num = hotel_clean$HOTEL.CLASS
hotel_clean$HOTEL.CLASS = factor(hotel_clean$HOTEL.CLASS)
hotel_clean$Pool = factor(hotel_clean$Pool)
hotel_clean$Gym = factor(hotel_clean$Gym)
hotel_clean$Airport.transportation = factor(hotel_clean$Airport.transportation)
hotel_clean$Bar = factor(hotel_clean$Bar...lounge)
rownames(hotel_clean) <- hotel_clean$name
```


```{r}
hotel_clean
```


```{r}
par(mfrow=c(1,4),cex.lab = 2,cex.axis =1) 
plot(Pool ~ HOTEL.CLASS, hotel_clean)
plot(Gym ~ HOTEL.CLASS, hotel_clean )
plot(Airport.transportation ~ HOTEL.CLASS, hotel_clean )
plot(Bar ~ HOTEL.CLASS, hotel_clean )
```

```{r}
png(file="IV_PLOT/Facility ratio.png",
width=1400, height=800)


par(mfrow=c(1,4),cex.lab = 2) 
plot(Pool ~ HOTEL.CLASS, hotel_clean)
plot(Gym ~ HOTEL.CLASS, hotel_clean )
plot(Airport.transportation ~ HOTEL.CLASS, hotel_clean )
plot(Bar ~ HOTEL.CLASS, hotel_clean )
dev.off()
```
```{r}
plot(density(hotel_clean$price),main="Price Density",xlab="Price ")
rug(hotel_clean$price)
hist(hotel_clean$price,freq=F,add=T,col="#D6604D")
```
```{r}
png(file="IV_PLOT/Price Density.png",
width=1200, height=800)

plot(density(hotel_clean$price),main="Price Density",xlab="Price ")
rug(hotel_clean$price)
hist(hotel_clean$price,freq=F,add=T,col="#D6604D")
dev.off()
```


```{r}
density
```

```{r}
colnames(hotel_clean)
```

```{r}
hotelcorr = hotel_clean[,c(17,18,19,16)]
hotelcorr$hotellevel = hotel_clean$HOTEL.CLASS.num>=4
```

```{r}
pairs(hotelcorr[,-c(5)], panel = panel.smooth, main = "Correlation between hotel features", col = hotel_clean$HOTEL.CLASS.num)
```
```{r}
png(file="IV_PLOT/Correlation between hotel features.png",
width=1200, height=800)

pairs(hotelcorr[,-c(5)], panel = panel.smooth, main = "Correlation between hotel features", col = hotel_clean$HOTEL.CLASS.num)
dev.off()
```


```{r}
model0 <- lm(price ~ summary + Location + X.Cleanliness + Service + Value + Pool + Bar +Airport.transportation+Gym+HOTEL.CLASS+Great.for.walkers+Nearby.restaurants+Attractions,data =  hotel_clean)
summary(model0)
```
```{r}
step(model0)
```
```{r}
model1 = lm(formula = price ~ Location + HOTEL.CLASS + Great.for.walkers, 
    data = hotel_clean)
summary(model1)
anova(model1)
```
```{r}
library(ggplot2)
dfq1 = data.frame(price=log(hotel_clean[,16]),location_score = log(hotel_clean[,17]+hotel_clean[,18]+hotel_clean[,19]+hotel_clean[,4]*5),hotel_class = factor(hotel_clean[,12]))
ggplot(dfq1, aes(x = price, y = location_score,color = hotel_class,shape=hotel_class,size = 2)) + 
geom_point(aes(color = hotel_class))+theme_grey(base_size = 22)
```
```{r}
png(file="IV_PLOT/model visual.png",
width=1200, height=800)

dfq1 = data.frame(price=log(hotel_clean[,16]),location_score = log(hotel_clean[,17]+hotel_clean[,18]+hotel_clean[,19]+hotel_clean[,4]*20),hotel_class = factor(hotel_clean[,12]))
ggplot(dfq1, aes(x = price, y = location_score,color = hotel_class,shape=hotel_class,size = 2)) + 
geom_point(aes(color = hotel_class))+theme_grey(base_size = 22)
dev.off()
```


```{r}
par(mfrow=c(2,2),cex.lab = 2,cex.axis =1,cex = 1) 
plot(model1)

```


```{r}
png(file="IV_PLOT/model diagnosis.png",
width=1200, height=800)
par(mfrow=c(2,2),cex.lab = 2,cex.axis =1,cex = 1) 
plot(model1)
dev.off()

```

```{r}
png(file="IV_PLOT/model diagnosis-1.png",
width=1200, height=800)
plot(model1,cex.lab=1.5, cex.axis=1.5, cex.main=1.5, cex.sub=1.5,cex=2)
dev.off()
```

```{r}

plot(model1,which = 1,id.cex = 2)
```
```{r}
png(file="IV_PLOT/model diagnosis-1.png",
width=1200, height=800)
plot(model1,which = 1)
dev.off()
```

```{r}
colors <- c("#999999", "#E69F00", "#56B4E9")
colors <- colors[as.numeric(iris$Species)]
scatterplot3d(iris[,1:3], pch = 16, color=colors)
```


```{r}
label = rep(0,nrow(hotel_clean))
for (i in 1:nrow(hotel_clean)) {
  #print(hotel_clean$HOTEL.CLASS.num[i])
  if (as.numeric(hotel_clean$HOTEL.CLASS.num[i])  == 2){
    label[i] = 1
  }
  else if(as.numeric(hotel_clean$HOTEL.CLASS.num[i]) == 3){
    label[i] = 1}
  else if(as.numeric(hotel_clean$HOTEL.CLASS.num[i]) == 3.5){
    #print("######")
    label[i] = 2}
  else if(as.numeric(hotel_clean$HOTEL.CLASS.num[i]) == 4){
   #print("######")
    label[i] = 2}
  else if(as.numeric(hotel_clean$HOTEL.CLASS.num[i]) == 4.5){
    label[i] = 3}
  else if(as.numeric(hotel_clean$HOTEL.CLASS.num[i]) == 5){
    label[i] = 3}
  
  
}
#print(label)
colors <- c("#999999", "#E69F00", "#56B4E9")
color = rep(0,nrow(hotel_clean))
for (i in 1:nrow(hotel_clean)) {
  if (label[i] == 1){
    color[i] = colors[1]
  }
  else if(label[i] == 2){
    color[i] = colors[2]
  }
  else if(label[i] == 3){
    color[i] = colors[3]}

}
#colors <- colors[as.numeric(label)]
Hotel_review_score = hotel_clean[,3]
location_score = hotel_clean[,17]+hotel_clean[,18]+hotel_clean[,19]+hotel_clean[,4]*10
location_score = log(location_score)
price = log(hotel_clean[,16])
s3d = scatterplot3d(location_score,Hotel_review_score,price, color=color,main = "3D Plot - Requirements, Accuracy & Time",
              xlab = "Number of requirements", ylab = "Accuracy", zlab = "Time", pch = label, angle = 45)
legend("topright",s3d$xyz.convert(18, 0, 12),pch = label,
       legend = c("budget hotel","mid-range hotel","luxurious hotel"), cex = 1.1,yjust=0
       )
```
```{r}
#print(label)
colors <- c("red", "green", "blue")
color = rep(0,nrow(hotel_clean))
for (i in 1:nrow(hotel_clean)) {
  if (label[i] == 1){
    color[i] = colors[1]
  }
  else if(label[i] == 2){
    color[i] = colors[2]
  }
  else if(label[i] == 3){
    color[i] = colors[3]}

}


Hotel_review_score = hotel_clean[,3]
location_score = hotel_clean[,17]+hotel_clean[,18]+hotel_clean[,19]+hotel_clean[,4]*10
location_score = log(location_score)
price = log(hotel_clean[,16])
s3d = scatterplot3d(location_score,Hotel_review_score,price, color=color,
              xlab = "Location", ylab = "Review", zlab = "Price", pch = label, angle = 45,type="h")
legend("top",s3d$xyz.convert(18, 0, 12),pch = c(1,2,3), 
       legend = c("budget hotel","mid-range hotel","luxurious hotel"), cex = 1.1,yjust=0
       )
```

```{r}
png(file="IV_PLOT/3D.png",
width=1200, height=800)
Hotel_review_score = hotel_clean[,3]
location_score = hotel_clean[,17]+hotel_clean[,18]+hotel_clean[,19]+hotel_clean[,4]*10
location_score = log(location_score)
price = log(hotel_clean[,16])
s3d = scatterplot3d(location_score,Hotel_review_score,price, color=color,
              xlab = "Location", ylab = "Review", zlab = "Price", pch = label, angle = 45,type="h",cex.symbols=2,cex.lab =2)
legend("top",s3d$xyz.convert(18, 0, 12),pch = c(1,2,3), 
       legend = c("budget hotel","mid-range hotel","luxurious hotel"), cex = 1.1,yjust=0
       )
dev.off()
```

```{r}
png(file="IV_PLOT/3D1.png",
width=1200, height=800)
Hotel_review_score = hotel_clean[,3]
location_score = hotel_clean[,17]+hotel_clean[,18]+hotel_clean[,19]+hotel_clean[,4]*10
location_score = log(location_score)
price = log(hotel_clean[,16])
s3d = scatterplot3d(price,location_score,Hotel_review_score, color=color,
              xlab = "Location", ylab = "Review", zlab = "Price", pch = label, angle = 45,type="h",size = 2)
legend("top",s3d$xyz.convert(18, 0, 12),pch = c(1,2,3), 
       legend = c("budget hotel","mid-range hotel","luxurious hotel"), cex = 1.1,yjust=0
       )
dev.off()
```
```

```{r}
png(file="IV_PLOT/model diagnosis-3.png",
width=1200, height=800)
plot(model1,which = 3)
dev.off()
```

```{r}
png(file="IV_PLOT/model diagnosis-4.png",
width=1200, height=800)
plot(model1,which = 4)
dev.off()
```

